name: CI

on:
  pull_request:
    branches:
      - main
      - master
      - develop
      - staging
  push:
    branches:
      - main
      - master
      - develop

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yml
